adobe/helix-static

src/index.js, test/fixtures/recordings/Static-Delivery-Action-unittest_2612775662/main-without-parameters-reports-status_2880301152/recording.har, test/testStatic.js
=> feat(monitoring): report status, reponse time and version to Pingdom

package-lock.json, package.json, src/index.js, test/testStatic.js
=> fix(caching): add surrogate key

src/index.js
=> fix(log): fix logger

src/index.js, test/testStatic.js
=> fix(index): report version on GET /

src/index.js, test/fixtures/recordings/Static-Delivery-Action-integrationtest_150101738/deliver-CSS-file-from-ref_1258525718/recording.har, test/testStatic.js
=> fix(cache): compute surrogate-key based on branch if present

src/index.js, test/fixtures/recordings/Static-Delivery-Action-unittest_2612775662/main-returns-static-file-from-private-GitHub-repo-gh-token-via-header-_2891396832/recording.har, test/fixtures/recordings/Static-Delivery-Action-unittest_2612775662/main-returns-static-file-from-private-GitHub-repo-gh-token-via-param-_4206500316/recording.har, test/fixtures/recordings/Static-Delivery-Action-unittest_2612775662/main-returns-static-file-from-private-GitHub-repo_575155986/recording.har, test/testStatic.js
=> feat(static): support authenticated Github access

.circleci/config.yml, package-lock.json, package.json, src/index.js, test/testStatic.js
=> chore(package): replace helix-pingdom-status with helix-status (#57)

src/index.js
=> Change logging level of 404 request

CONTRIBUTING.md
Enhanced readability via minor grammar / spelling changes.
=> docs: CONTRIBUTING.md grammar revisions

package.json, src/index.js
=> feat(log): log memory and filehandle stats

src/index.js
=> feat(status): add concurrency level and action uuid

src/font-proxy.js, src/index.js, test/fixtures/recordings/Adobe-Fonts-Proxy-Test-unitttest_2193308915/Delivers-404-for-missing-kit_804522628/recording.har, test/fixtures/recordings/Adobe-Fonts-Proxy-Test-unitttest_2193308915/Delivers-rewritten-Kit_2154414463/recording.har, test/fixtures/recordings/Static-Delivery-Action-integrationtest_150101738/deliver-Typekit-CSS-file_3273388205/recording.har, test/testFontProxy.js, test/testStatic.js
=> feat(css): enable Adobe Fonts CSS serving and rewriting

src/font-proxy.js, test/testFontProxy.js
Removed tracking pixel, added font-display swap, refactored for better re-use of walkDecls
fix: #196
=> feat(fonts): remove extra tracking css import call

src/index.js, test/testStatic.js
Fix for #266 and https://github.com/adobe/helix-pages/issues/240
=> Allow well known URLs

src/index.js
=> fix(index): report 500 from received from backend as 502

src/index.js, test/fixtures/recordings/Static-Delivery-Action-integrationtest_150101738/deliver-CSS-file-from-ref_1258525718/recording.har, test/fixtures/recordings/Static-Delivery-Action-integrationtest_150101738/deliver-CSS-file_2365649133/recording.har, test/fixtures/recordings/Static-Delivery-Action-unittest_2612775662/main-returns-static-file-from-GitHub_2955134363/recording.har, test/testStatic.js
strips all double slashes, e.g. in combinations of ref and path
fixes https://github.com/adobe/helix-pages/issues/296
=> fix(static): properly sanitize URLs to avoid issues due to double-slashes

src/font-proxy.js, test/testFontProxy.js
=> fix(font): handle exceptions from request

src/font-proxy.js, test/testStatic.js
=> fix(font): create new fetch context for each invocation

src/github-fetcher.js
=> feat: return 504 on connect timeout

package-lock.json, package.json, test/integration.test.js, test/post-deploy-utils.js, test/post-deploy.test.js, test/utils.js
=> chore: adding tests for yaml

src/github-fetcher.js, test/fixtures/recordings/Static-Delivery-Action-unittest_2612775662/main-returns-static-file-via-github-pages_4015650603/recording.har, test/static.test.js
adds support for gh-pages using the branch name to select a different github _root_.
see https://github.com/adobe/helix-home/issues/191
=> feat(github): add support for github pages
